<?php
$pageTitle = 'Bone Setting | Daliya Ayurvedics';
$activePage = 'bone-setting';
include __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow">Traditional bone setting</span><h1>Bone setting care by Hanshi Ajayakumar Nair.</h1><p>Learn how traditional bone setting can support alignment, pain relief and mobility when selected carefully for the patient’s condition.</p></div></section>
<section class="section-pad"><div class="container split-grid"><div><h2>About bone setting</h2><p>Bone setting is a traditional hands-on therapy focused on musculoskeletal balance. It may include careful manual assessment, gentle corrections, herbal oil support, bandaging guidance, rest advice and follow-up exercises when appropriate.</p><p>At Daliya Ayurvedics, patient safety and clarity are important. Severe injuries, fractures, heavy swelling, open wounds or emergency symptoms should be evaluated by emergency medical services or an orthopaedic specialist immediately.</p></div><div class="profile-card"><div class="avatar">HA</div><h2>Hanshi Ajayakumar Nair</h2><p>Traditional bone setter</p><p>Known for patient-focused explanations and practical recovery guidance, Hanshi Ajayakumar Nair provides bone setting support for suitable musculoskeletal concerns.</p></div></div></section>
<section class="section-pad soft-bg"><div class="container"><div class="section-heading"><span class="eyebrow">Therapy benefits</span><h2>Why patients choose traditional bone setting</h2></div><div class="card-grid three"><article class="info-card"><h3>Mobility support</h3><p>Helps selected patients improve movement comfort with manual care and guided rehabilitation.</p></article><article class="info-card"><h3>Natural pain relief</h3><p>Uses traditional techniques and Ayurvedic support to reduce discomfort where suitable.</p></article><article class="info-card"><h3>Recovery guidance</h3><p>Includes posture, rest, exercise and follow-up advice for better long-term outcomes.</p></article></div></div></section>
<?php include __DIR__ . '/includes/footer.php'; ?>
